//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROMVault2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ROMVault2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  , .
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Keyword .
        /// </summary>
        internal static string DatCmpReader_LoadDirFromDat_Error_Keyword {
            get {
                return ResourceManager.GetString("DatCmpReader_LoadDirFromDat_Error_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not know in dir.
        /// </summary>
        internal static string DatCmpReader_LoadDirFromDat_not_know_in_dir {
            get {
                return ResourceManager.GetString("DatCmpReader_LoadDirFromDat_not_know_in_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not found as first object in ( ).
        /// </summary>
        internal static string DatCmpReader_LoadGameFromDat_Name_not_found_as_first_object_in {
            get {
                return ResourceManager.GetString("DatCmpReader_LoadGameFromDat_Name_not_found_as_first_object_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( not found after game.
        /// </summary>
        internal static string DatCmpReader_LoadGameFromDat_not_found_after_game {
            get {
                return ResourceManager.GetString("DatCmpReader_LoadGameFromDat_not_found_after_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; not known in game.
        /// </summary>
        internal static string DatCmpReader_LoadGameFromDat_not_known_in_game {
            get {
                return ResourceManager.GetString("DatCmpReader_LoadGameFromDat_not_known_in_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( not found after clrmamepro.
        /// </summary>
        internal static string DatCmpReader_LoadHeaderFromDat_not_found_after_clrmamepro {
            get {
                return ResourceManager.GetString("DatCmpReader_LoadHeaderFromDat_not_found_after_clrmamepro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; not known in clrmamepro.
        /// </summary>
        internal static string DatCmpReader_LoadHeaderFromDat_not_known_in_clrmamepro {
            get {
                return ResourceManager.GetString("DatCmpReader_LoadHeaderFromDat_not_known_in_clrmamepro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( not found after rom.
        /// </summary>
        internal static string DatCmpReader_LoadRomFromDat_not_found_after_rom {
            get {
                return ResourceManager.GetString("DatCmpReader_LoadRomFromDat_not_found_after_rom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; not known in rom.
        /// </summary>
        internal static string DatCmpReader_LoadRomFromDat_not_known_in_rom {
            get {
                return ResourceManager.GetString("DatCmpReader_LoadRomFromDat_not_known_in_rom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: key word &apos;.
        /// </summary>
        internal static string DatCmpReader_ReadDat_Error_keyword {
            get {
                return ResourceManager.GetString("DatCmpReader_ReadDat_Error_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; not known.
        /// </summary>
        internal static string DatCmpReader_ReadDat_not_known {
            get {
                return ResourceManager.GetString("DatCmpReader_ReadDat_not_known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error dat found on item listed as not in dat.
        /// </summary>
        internal static string DatUpdate_ClearOldDats_Error_dat_found_on_item_listed_as_not_in_dat {
            get {
                return ResourceManager.GetString("DatUpdate_ClearOldDats_Error_dat_found_on_item_listed_as_not_in_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got to a non dir when checking Dir&apos;s for dats to remove.
        /// </summary>
        internal static string DatUpdate_ClearOldDats_Got_to_a_non_dir_when_checking_Dir_s_for_dats_to_remove {
            get {
                return ResourceManager.GetString("DatUpdate_ClearOldDats_Got_to_a_non_dir_when_checking_Dir_s_for_dats_to_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is bad, rBase.Dat is set to a dat, and rBase.DatStatus is not.
        /// </summary>
        internal static string DatUpdate_ClearOldDats_This_is_bad__rBase_Dat_is_set_to_a_dat_and_rBase_DatStatus_is_not {
            get {
                return ResourceManager.GetString("DatUpdate_ClearOldDats_This_is_bad__rBase_Dat_is_set_to_a_dat_and_rBase_DatStatus" +
                        "_is_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown File Delete Test .
        /// </summary>
        internal static string DatUpdate_ClearOldDats_Unknown_File_Delete_Test {
            get {
                return ResourceManager.GetString("DatUpdate_ClearOldDats_Unknown_File_Delete_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file setup.
        /// </summary>
        internal static string DatUpdate_ClearOldDats_Unknown_file_setup {
            get {
                return ResourceManager.GetString("DatUpdate_ClearOldDats_Unknown_file_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should also never happen..
        /// </summary>
        internal static string DatUpdate_ClearRemovedDatsFromTheDb_This_should_also_never_happen {
            get {
                return ResourceManager.GetString("DatUpdate_ClearRemovedDatsFromTheDb_This_should_also_never_happen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Logic.
        /// </summary>
        internal static string DatUpdate_MergeInDat_Error_in_Logic {
            get {
                return ResourceManager.GetString("DatUpdate_MergeInDat_Error_in_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown Update Dat Status .
        /// </summary>
        internal static string DatUpdate_MergeInDat_Unkown_Update_Dat_Status {
            get {
                return ResourceManager.GetString("DatUpdate_MergeInDat_Unkown_Update_Dat_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Merge Status.
        /// </summary>
        internal static string DatUpdate_UpdateDatFile_Unknown_Merge_Status {
            get {
                return ResourceManager.GetString("DatUpdate_UpdateDatFile_Unknown_Merge_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; Directory will be ignored..
        /// </summary>
        internal static string DatUpdate_UpdateDatList_Directory_will_be_ignored {
            get {
                return ResourceManager.GetString("DatUpdate_UpdateDatList_Directory_will_be_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Directories found in &apos;.
        /// </summary>
        internal static string DatUpdate_UpdateDatList_Empty_Directories_found_in {
            get {
                return ResourceManager.GetString("DatUpdate_UpdateDatList_Empty_Directories_found_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Deleting a DAT that should already be deleted.
        /// </summary>
        internal static string DatUpdate_UpdateDatList_ERROR_Deleting_a_DAT_that_should_already_be_deleted {
            get {
                return ResourceManager.GetString("DatUpdate_UpdateDatList_ERROR_Deleting_a_DAT_that_should_already_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Not Found..
        /// </summary>
        internal static string DatUpdate_UpdateDatList_Not_Found {
            get {
                return ResourceManager.GetString("DatUpdate_UpdateDatList_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: .
        /// </summary>
        internal static string DatUpdate_UpdateDatList_Path {
            get {
                return ResourceManager.GetString("DatUpdate_UpdateDatList_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RomValue Scan Error:.
        /// </summary>
        internal static string DatUpdate_UpdateDatList_RomValue_Scan_Error {
            get {
                return ResourceManager.GetString("DatUpdate_UpdateDatList_RomValue_Scan_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Cache version is out of date you should now rescan your dat directory and roms directory..
        /// </summary>
        internal static string DB_Read_Data_Cache_version_is_out_of_date_you_should_now_rescan_your_dat_directory_and_roms_directory_ {
            get {
                return ResourceManager.GetString("DB_Read_Data_Cache_version_is_out_of_date_you_should_now_rescan_your_dat_director" +
                        "y_and_roms_directory_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in File Scanning Code..
        /// </summary>
        internal static string FileScanning_CheckADir_Error_in_File_Scanning_Code {
            get {
                return ResourceManager.GetString("FileScanning_CheckADir_Error_in_File_Scanning_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Case .
        /// </summary>
        internal static string FindFixes_ListCheck_Error_Case {
            get {
                return ResourceManager.GetString("FindFixes_ListCheck_Error_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Set For .
        /// </summary>
        internal static string FindFixes_ListCheck_Nothing_Set_For {
            get {
                return ResourceManager.GetString("FindFixes_ListCheck_Nothing_Set_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown test status .
        /// </summary>
        internal static string FindFixes_ListCheck_Unknown_test_status {
            get {
                return ResourceManager.GetString("FindFixes_ListCheck_Unknown_test_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown result type.
        /// </summary>
        internal static string FixFiles_FixDirChildren_Unknown_result_type {
            get {
                return ResourceManager.GetString("FixFiles_FixDirChildren_Unknown_result_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  But the case of the unknown file is wrong. Rescan and try agian..
        /// </summary>
        internal static string FixFiles_FixFile__But_the_case_of_the_unknown_file_is_wrong_Rescan_and_try_agian {
            get {
                return ResourceManager.GetString("FixFiles_FixFile__But_the_case_of_the_unknown_file_is_wrong_Rescan_and_try_agian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Did you manualy fix this file without rescanning?.
        /// </summary>
        internal static string FixFiles_FixFile__Did_you_manualy_fix_this_file_without_rescanning {
            get {
                return ResourceManager.GetString("FixFiles_FixFile__Did_you_manualy_fix_this_file_without_rescanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to fix a file that already exists .
        /// </summary>
        internal static string FixFiles_FixFile_Trying_to_fix_a_file_that_already_exists {
            get {
                return ResourceManager.GetString("FixFiles_FixFile_Trying_to_fix_a_file_that_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Find the file used to fix .
        /// </summary>
        internal static string FixFiles_FixFile_Unable_to_Find_the_file_used_to_fix {
            get {
                return ResourceManager.GetString("FixFiles_FixFile_Unable_to_Find_the_file_used_to_fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown fix file type .
        /// </summary>
        internal static string FixFiles_FixFile_Unknown_fix_file_type {
            get {
                return ResourceManager.GetString("FixFiles_FixFile_Unknown_fix_file_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file Fix.
        /// </summary>
        internal static string FixFiles_FixFile_Unsupported_file_Fix {
            get {
                return ResourceManager.GetString("FixFiles_FixFile_Unsupported_file_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  : .
        /// </summary>
        internal static string FixFiles_FixZip_Colon {
            get {
                return ResourceManager.GetString("FixFiles_FixZip_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding Fixing Rom, Database is corrupt..
        /// </summary>
        internal static string FixFiles_FixZip_Error_finding_Fixing_Rom_Database_is_corrupt {
            get {
                return ResourceManager.GetString("FixFiles_FixZip_Error_finding_Fixing_Rom_Database_is_corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Fix Rom Status .
        /// </summary>
        internal static string FixFiles_FixZip_Error_in_Fix_Rom_Status {
            get {
                return ResourceManager.GetString("FixFiles_FixZip_Error_in_Fix_Rom_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing zip .
        /// </summary>
        internal static string FixFiles_FixZip_Error_processing_zip {
            get {
                return ResourceManager.GetString("FixFiles_FixZip_Error_processing_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Delete case should never happen, help .
        /// </summary>
        internal static string FixFiles_FixZip_This_Delete_case_should_never_happen__help {
            get {
                return ResourceManager.GetString("FixFiles_FixZip_This_Delete_case_should_never_happen__help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Delete case should never happen, you do not delete a rom you collect..
        /// </summary>
        internal static string FixFiles_FixZip_This_Delete_case_should_never_happen__you_do_not_delete_a_rom_you_collect {
            get {
                return ResourceManager.GetString("FixFiles_FixZip_This_Delete_case_should_never_happen__you_do_not_delete_a_rom_you" +
                        "_collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type.
        /// </summary>
        internal static string FixFiles_FixZip_Unknown_type {
            get {
                return ResourceManager.GetString("FixFiles_FixZip_Unknown_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  did you delete it?.
        /// </summary>
        internal static string FixFiles_OpenOriginalZip_did_you_delete_it {
            get {
                return ResourceManager.GetString("FixFiles_OpenOriginalZip_did_you_delete_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found :.
        /// </summary>
        internal static string FixFiles_OpenOriginalZip_File_not_found {
            get {
                return ResourceManager.GetString("FixFiles_OpenOriginalZip_File_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File TimeStamp has changed in file .
        /// </summary>
        internal static string FixFiles_OpenOriginalZip_File_TimeStamp_has_changed_in_file {
            get {
                return ResourceManager.GetString("FixFiles_OpenOriginalZip_File_TimeStamp_has_changed_in_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an unknown file :.
        /// </summary>
        internal static string FixFiles_OpenOriginalZip_Found_an_unknown_file {
            get {
                return ResourceManager.GetString("FixFiles_OpenOriginalZip_Found_an_unknown_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to open an unscanned file :.
        /// </summary>
        internal static string FixFiles_OpenOriginalZip_Trying_to_open_an_unscanned_file {
            get {
                return ResourceManager.GetString("FixFiles_OpenOriginalZip_Trying_to_open_an_unscanned_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown File Open Type..
        /// </summary>
        internal static string FixFiles_OpenOriginalZip_Unknown_File_Open_Type {
            get {
                return ResourceManager.GetString("FixFiles_OpenOriginalZip_Unknown_File_Open_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to fix unscanned dir&apos;s.
        /// </summary>
        internal static string FixFiles_PerformFixes_Trying_to_fix_unscanned_dir_s {
            get {
                return ResourceManager.GetString("FixFiles_PerformFixes_Trying_to_fix_unscanned_dir_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set ROM DIR.
        /// </summary>
        internal static string FrmMain_DirTreeRvSelected_Set_ROM_DIR {
            get {
                return ResourceManager.GetString("FrmMain_DirTreeRvSelected_Set_ROM_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type Missing .
        /// </summary>
        internal static string FrmMain_UpdateRomGrid_File_Type_Missing_ {
            get {
                return ResourceManager.GetString("FrmMain_UpdateRomGrid_File_Type_Missing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Directory Settings.
        /// </summary>
        internal static string FrmSetDir_BtnDeleteSelectedClick_Directory_Settings {
            get {
                return ResourceManager.GetString("FrmSetDir_BtnDeleteSelectedClick_Directory_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROMVault Rom Location.
        /// </summary>
        internal static string FrmSetDir_BtnDeleteSelectedClick_ROMVault_Rom_Location {
            get {
                return ResourceManager.GetString("FrmSetDir_BtnDeleteSelectedClick_ROMVault_Rom_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete the .
        /// </summary>
        internal static string FrmSetDir_BtnDeleteSelectedClick_You_cannot_delete_the {
            get {
                return ResourceManager.GetString("FrmSetDir_BtnDeleteSelectedClick_You_cannot_delete_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder for This Rom Set.
        /// </summary>
        internal static string FrmSetDir_BtnSetRomLocationClick_Please_select_a_folder_for_This_Rom_Set {
            get {
                return ResourceManager.GetString("FrmSetDir_BtnSetRomLocationClick_Please_select_a_folder_for_This_Rom_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Existing Directory Mapping.
        /// </summary>
        internal static string FrmSetDir_DataGridGamesDoubleClick_Edit_Existing_Directory_Mapping {
            get {
                return ResourceManager.GetString("FrmSetDir_DataGridGamesDoubleClick_Edit_Existing_Directory_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder for DAT Root.
        /// </summary>
        internal static string FrmSettings_BtnDatClick_Please_select_a_folder_for_DAT_Root {
            get {
                return ResourceManager.GetString("FrmSettings_BtnDatClick_Please_select_a_folder_for_DAT_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new release download now from .
        /// </summary>
        internal static string Program_Main_There_is_a_new_release_download_now_from {
            get {
                return ResourceManager.GetString("Program_Main_There_is_a_new_release_download_now_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not Authorised to use this program..
        /// </summary>
        internal static string Program_Main_You_are_not_Authorised_to_use_this_program {
            get {
                return ResourceManager.GetString("Program_Main_You_are_not_Authorised_to_use_this_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a &apos;user - &lt;NAME&gt;.xml&apos; file to use ROMVault.
        /// </summary>
        internal static string Program_Main_You_must_have_a__user____NAME__xml__file_to_use_ROMVault {
            get {
                return ResourceManager.GetString("Program_Main_You_must_have_a__user____NAME__xml__file_to_use_ROMVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ProgressWindowFix_DoDone_Close {
            get {
                return ResourceManager.GetString("ProgressWindowFix_DoDone_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string ProgressWindowFix_OnClosing_Cancelling {
            get {
                return ResourceManager.GetString("ProgressWindowFix_OnClosing_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder for Dats.
        /// </summary>
        internal static string Report_MakeFixFiles_Please_select_a_folder_for_Dats {
            get {
                return ResourceManager.GetString("Report_MakeFixFiles_Please_select_a_folder_for_Dats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  , .
        /// </summary>
        internal static string RvBase_Check {
            get {
                return ResourceManager.GetString("RvBase_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error Status File .
        /// </summary>
        internal static string RvBase_Check_Unknown_Error_Status_File {
            get {
                return ResourceManager.GetString("RvBase_Check_Unknown_Error_Status_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat found without an index.
        /// </summary>
        internal static string RvBase_Read_Dat_found_without_an_index {
            get {
                return ResourceManager.GetString("RvBase_Read_Dat_found_without_an_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Set Got Status .
        /// </summary>
        internal static string RvBase_SetGot_Unknown_Set_Got_Status {
            get {
                return ResourceManager.GetString("RvBase_SetGot_Unknown_Set_Got_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Dir with a dat list.
        /// </summary>
        internal static string RvDir_ClearDat_Clearing_Dir_with_a_dat_list {
            get {
                return ResourceManager.GetString("RvDir_ClearDat_Clearing_Dir_with_a_dat_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Dir with a dat list.
        /// </summary>
        internal static string RvDir_SetDat_Setting_Dir_with_a_dat_list {
            get {
                return ResourceManager.GetString("RvDir_SetDat_Setting_Dir_with_a_dat_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count went negative..
        /// </summary>
        internal static string RvDir_UpdateArrGotStatus_Count_went_negative {
            get {
                return ResourceManager.GetString("RvDir_UpdateArrGotStatus_Count_went_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Reset Got status .
        /// </summary>
        internal static string Utils_ResetGotStatus_Unknown_Reset_Got_status {
            get {
                return ResourceManager.GetString("Utils_ResetGotStatus_Unknown_Reset_Got_status", resourceCulture);
            }
        }
    }
}
